[tool.poetry]
name = "graia-scheduler"
version = "0.0.5"
description = "a scheduler for graia framework"
authors = ["GreyElaina <31543961+GreyElaina@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "graia", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.7"
graia-broadcast = "^0.12.1"
croniter = "^0.3.36"
dataclasses = {python = "<3.7", version = "*"}

[tool.poetry.dev-dependencies]
graia-saya = "^0.0.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
saya = ['graia-saya']